@warning_ignore("unused_signal")
extends Node

signal battle_started(node_id: String)
signal battle_finished(node_id: String, success: bool)
signal enemy_killed(enemy_id: String)
signal node_changed(node_id: String)
signal player_hp_changed(current_hp: float, max_hp: float)
signal combat_state_changed(state_text: String)
signal resources_changed()
signal core_skill_changed(skill_id: String)
signal config_loaded()
signal equipment_changed()
signal loot_summary_changed(summary_text: String)
signal inventory_changed()
signal offline_report_ready(report_text: String)
signal research_changed()
signal research_upgraded(node_id: String, new_level: int)
signal codex_changed()
signal loot_target_changed()
signal daily_goals_changed()
signal legendary_discovered(legendary_affix_id: String, legendary_name: String, is_tracked_target: bool)
signal stage_event_ready(event_data: Dictionary)
signal stage_event_closed()
signal combat_highlight_requested(highlight_data: Dictionary)
signal set_bonus_changed(set_summary: Dictionary)
signal cube_operation_completed(operation_result: Dictionary)
signal martial_codex_changed(state: Dictionary)
signal rift_run_started(rift_state: Dictionary)
signal rift_run_finished(result: Dictionary)
signal gem_upgraded(gem_id: String, new_level: int)
signal paragon_changed(summary: Dictionary)
signal season_reborn(summary: Dictionary)
signal ui_panel_requested(panel_id: String)
signal ui_close_requested()
signal ui_state_changed(active_panel_id: String, blocking_input: bool)

var ui_blocking_input: bool = false
